# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

#stages:
#- stage: Deploy
#  pool: 
#   name: EG SelfHosted
   #demands:
   # - agent.name -equals SP-EGDEV0333

trigger:
- master

pool:
  vmImage: 'windows-latest'
  #name: JobOffice SelfHosted

variables:
  solution: 'src/MethodBoundaryAspect.Fody.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

#- task: NuGetAuthenticate@1
#  inputs:
#    forceReinstallCredentialProvider: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/src/MethodBoundaryAspect/**/*.nupkg;!$(Build.SourcesDirectory)/src/MethodBoundaryAspect/**/*.snupkg'
    nuGetFeedType: 'internal'
    #platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'