# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

stages:
- stage: Deploy
  pool: 
   name: EG SelfHosted
   #demands:
   # - agent.name -equals SP-EGDEV0333

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'src/MethodBoundaryAspect.Fody.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@1
  inputs:
    forceReinstallCredentialProvider: true
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    #packagesToPush: '$(Build.ArtifactStagingDirectory)\**\*.nupkg;!$(Build.ArtifactStagingDirectory)\**\*.snupkg'
    packagesToPush: '$(Build.SourcesDirectory)/src/MethodBoundaryAspect/**/*.nupkg;!$(Build.SourcesDirectory)/src/MethodBoundaryAspect/**/*.snupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'fc916700-ae2c-4022-82bf-073da5f2dc77/ded83ae7-1057-42bb-84ad-d1daaf82446e'
    #platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'